# Generated by Django 4.0.5 on 2022-06-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0001_initial'),
    ]

    operations = [
    ]
