# Generated by Django 4.0.5 on 2022-06-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0002_initial'),
    ]

    operations = [
    ]
